apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
    release: metrics
    app.kubernetes.io/name: web
  name: web-service
  namespace: web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
     app.kubernetes.io/name: web
  type: NodePort