apiVersion: v1
kind: Secret
metadata:
  name: web-mysql-secrets
  namespace: web
type: Opaque
data:
  mysql_database: d2ViX2Ri
  mysql_host: bXlzcWwtc2VydmVyLm15c3FsLXNlcnZlci5zdmMuY2x1c3Rlci5sb2NhbDozMzA2
  mysql_password: d2ViX3VzZXI=
  mysql_user: d2ViX3VzZXI=
