apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: web
  project: default
  source:
    path: applications/web/_release/env/dev
    repoURL: https://github.com/marcelosf89/gitops-local.git
    targetRevision: main
  syncPolicy:
    automated: {}