apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: web
    app.kubernetes.io/name: web
  name: web
  namespace: web
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8484
          # readinessProbe:
          #   httpGet:
          #     scheme: HTTP
          #     path: /status
          #     port: 8484
          #   initialDelaySeconds: 3
          #   periodSeconds: 10
          envFrom:
            - secretRef:
                name: web-mysql-secrets
          resources:
            limits:
              memory: "128Mi"
            requests:
              cpu: "20m"
              memory: "128Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop: ["ALL"]
      restartPolicy: Always
