apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
    release: prom-stack
    app.kubernetes.io/name: web
  name: web-service
  namespace: web
spec:
  ports:
  - name: "8484"
    port: 8484
    targetPort: 8484
  selector:
     app.kubernetes.io/name: web
  type: NodePort