name: Build Webserver

on:
  push: 
    tags:
      - v0.*.*
    branches: [ main, feat/*, feature/* ]
    paths:
        - 'applications/web/src/**'
        - '.github/workflows/app-web.yml'

  workflow_dispatch:

env:
  app: web
  stage: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || 'dev' }}
 
jobs:
  build:
    
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.version.outputs.tag }}${{ steps.version.outputs.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
        
      - name: Get Version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 )
          if [ $stage = "prod" ]; 
            then
                SHA=
            else
                SHA=-$(echo ${{ github.sha }} | cut -c1-7 )
            fi          
          echo "tag=$TAG"  >> $GITHUB_OUTPUT
          echo "sha=$SHA"  >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build
        run: |
          make app-build app=$app

      - name: Security Scan 
        run: |
          make app-scan app=$app
          
  docker:
    needs:
        - build
    
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Docker Build
        run: |
          make app-docker-build app=$app version=${{ needs.build.outputs.build_id }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          make app-docker-push app=$app version=${{ needs.build.outputs.build_id }}


  deploy-helm:
    needs:
        - build
        - docker
    
    name: Deploy Helmchart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy helmchart to dev
        run: |
          make push-update-release app=$app version=${{ needs.build.outputs.build_id }} repo_appsets=${{ github.repository }} environment="dev"
